### ISSUE TITLE
Cannot subclass _TensorBase directly Error at first launch, import failed

### ISSUE THREAD

**Issue by ghost** [wootwootwootwoot/ComfyUI-RK-Sampler#1]
Hi,
Very excited to try these samplers! However I received the below error.
Python 3.11.9, Windows 11, please let me know what other info would help.

`Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-RK-Sampler\__init__.py", line 8, in <module>
    from .nodes import nodes_rk_sampler
  File "D:\ComfyUI\custom_nodes\ComfyUI-RK-Sampler\nodes\nodes_rk_sampler.py", line 4, in <module>
    import torchode
  File "D:\ComfyUI\venv\Lib\site-packages\torchode\__init__.py", line 5, in <module>
    from .adjoints import AutoDiffAdjoint, BacksolveAdjoint, JointBacksolveAdjoint
  File "D:\ComfyUI\venv\Lib\site-packages\torchode\adjoints.py", line 7, in <module>
    from .problems import InitialValueProblem
  File "D:\ComfyUI\venv\Lib\site-packages\torchode\problems.py", line 3, in <module>
    from .typing import *
  File "D:\ComfyUI\venv\Lib\site-packages\torchode\typing.py", line 4, in <module>
    from torchtyping import TensorType, is_float
  File "D:\ComfyUI\venv\Lib\site-packages\torchtyping\__init__.py", line 10, in <module>
    from .tensor_type import TensorType
  File "D:\ComfyUI\venv\Lib\site-packages\torchtyping\tensor_type.py", line 37, in <module>
    class TensorTypeMixin(metaclass=_TensorTypeMeta):
RuntimeError: Cannot subclass _TensorBase directly

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-RK-Sampler module for custom nodes: Cannot subclass _TensorBase directly`

**Comment by ghost** [comment]
For awareness, I tried installing via ComfyManager and then uninstalled that and tried full manual.
I did a pip install --upgrade torchode torchtyping (both repositories listed in the error message). 
I only see torchode in requirements. txt so not sure what else to try. 
No changes, just wanted you to know the troubleshooting steps I already took.

**Comment by memmaptensor** [comment]
Hi, this seems to be an issue with some builds of torch. I suggest upgrading your torch version too.

**Comment by ghost** [comment]
Thank you. I am on torch 2.5 nightly so very very updated. What is the torch requirement for this? It seems like this repository will need an update to continue working on new Torch versions.

**Comment by memmaptensor** [comment]
Latest stable should work. You should open an issue on https://github.com/pytorch/pytorch

**Comment by memmaptensor** [comment]
While it gets upstreamed you can use my fork. @LankyPoet 
`pip install -U --force-reinstall git+https://github.com/wootwootwootwoot/torchode.git@no-torchtyping`

There's an issue with torchtyping (used by torchode) not being compatible with the latest torch nightly.

**Comment by EnragedAntelope** [comment]
Thank you!

**Comment by memmaptensor** [comment]
Latest torchtyping shouldn't have this issue. If you still have this issue, upgrade it with `pip install -U torchtyping`
