### ISSUE TITLE
SciPy samplers error on MPS

### ISSUE THREAD

**Issue by Adreitz** [wootwootwootwoot/ComfyUI-RK-Sampler#5]
I've been experimenting since yesterday with these samplers used on MPS for Flux dev generations (M3 Max, MacOS 14.6.2, newest comfyui with torch 2.3.1). I just found that none of the SciPy samplers function. They all produce the following error as soon as comfy starts processing the queued generation:

!!! Exception during processing !!! can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/Users/adreitz/pinokio/api/ComfyUI/app/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/Users/adreitz/pinokio/api/ComfyUI/app/comfy_extras/nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/custom_nodes/ComfyUI-RK-Sampler/nodes/nodes_rk_sampler.py", line 381, in __call__
    return self._call_scipy(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable)
  File "/Users/adreitz/pinokio/api/ComfyUI/app/custom_nodes/ComfyUI-RK-Sampler/nodes/nodes_rk_sampler.py", line 276, in _call_scipy
    x: np.ndarray = x.to(c_device).numpy().astype(c_dtype)
TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by memmaptensor** [comment]
Fixed https://github.com/wootwootwootwoot/ComfyUI-RK-Sampler/commit/cc95fe408bae1145360ed49245442137ddbe8b0f
